        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 16 13:49:43 2012
        MODULE CAMPO2D__genmod
          INTERFACE 
            SUBROUTINE CAMPO2D(NNODES,NELEMENTS,NODPEL,SOLUTION,MATERIAL&
     &,CONECT,COOR_X,COOR_Y,SIGMAEXT,SIGMAINT,SIGMAMEM,GRAD_X,GRAD_Y,   &
     &GRADXEL_X,GRADXEL_Y)
              INTEGER(KIND=4) :: NODPEL
              INTEGER(KIND=4) :: NELEMENTS
              INTEGER(KIND=4) :: NNODES
              REAL(KIND=8) :: SOLUTION(NNODES)
              INTEGER(KIND=4) :: MATERIAL(NELEMENTS)
              INTEGER(KIND=4) :: CONECT(NELEMENTS,NODPEL)
              REAL(KIND=8) :: COOR_X(NNODES)
              REAL(KIND=8) :: COOR_Y(NNODES)
              REAL(KIND=8) :: SIGMAEXT
              REAL(KIND=8) :: SIGMAINT
              REAL(KIND=8) :: SIGMAMEM
              REAL(KIND=8) :: GRAD_X(NNODES)
              REAL(KIND=8) :: GRAD_Y(NNODES)
              REAL(KIND=8) :: GRADXEL_X(NELEMENTS)
              REAL(KIND=8) :: GRADXEL_Y(NELEMENTS)
            END SUBROUTINE CAMPO2D
          END INTERFACE 
        END MODULE CAMPO2D__genmod
