        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 16 15:19:05 2012
        MODULE CONTROL__genmod
          INTERFACE 
            SUBROUTINE CONTROL
              USE DEF_VARIABLES
            END SUBROUTINE CONTROL
          END INTERFACE 
        END MODULE CONTROL__genmod
