        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 16 13:49:44 2012
        MODULE LECTURA__genmod
          INTERFACE 
            SUBROUTINE LECTURA
            END SUBROUTINE LECTURA
          END INTERFACE 
        END MODULE LECTURA__genmod
