        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 16 19:20:15 2012
        MODULE TENSIONES__genmod
          INTERFACE 
            SUBROUTINE TENSIONES
              USE DEF_VARIABLES
            END SUBROUTINE TENSIONES
          END INTERFACE 
        END MODULE TENSIONES__genmod
