        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 16 19:20:15 2012
        MODULE DERIVADOS__genmod
          INTERFACE 
            SUBROUTINE DERIVADOS
              USE DEF_VARIABLES
            END SUBROUTINE DERIVADOS
          END INTERFACE 
        END MODULE DERIVADOS__genmod
