        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 16 13:49:44 2012
        MODULE FINALICE__genmod
          INTERFACE 
            SUBROUTINE FINALICE
            END SUBROUTINE FINALICE
          END INTERFACE 
        END MODULE FINALICE__genmod
