        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 16 13:49:43 2012
        MODULE LEE_SISTEMA__genmod
          INTERFACE 
            SUBROUTINE LEE_SISTEMA(ARCHI_SISTEMA,NNODES)
              CHARACTER(LEN=20) :: ARCHI_SISTEMA
              INTEGER(KIND=4) :: NNODES
            END SUBROUTINE LEE_SISTEMA
          END INTERFACE 
        END MODULE LEE_SISTEMA__genmod
