        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 16 13:49:43 2012
        MODULE LEEMALLA__genmod
          INTERFACE 
            SUBROUTINE LEEMALLA
            END SUBROUTINE LEEMALLA
          END INTERFACE 
        END MODULE LEEMALLA__genmod
