        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 16 18:39:12 2012
        MODULE SALIDA_SOL__genmod
          INTERFACE 
            SUBROUTINE SALIDA_SOL(SOLUCION)
              USE DEF_VARIABLES
              REAL(KIND=8) :: SOLUCION(NNODES)
            END SUBROUTINE SALIDA_SOL
          END INTERFACE 
        END MODULE SALIDA_SOL__genmod
