        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 16 18:39:12 2012
        MODULE SALIDA_TENSION__genmod
          INTERFACE 
            SUBROUTINE SALIDA_TENSION(SOLUCION)
              USE DEF_VARIABLES
              REAL(KIND=8) :: SOLUCION(2*NNODES)
            END SUBROUTINE SALIDA_TENSION
          END INTERFACE 
        END MODULE SALIDA_TENSION__genmod
